name: jasonzenger
favicon: null
layout_spectrum: 0.2514482559636235
typography_spectrum: 0.45172458910383284
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6022561336867511
  lightness: 0.6763624302111566
  saturation: 0.9560378587339073
  rhythmicContrast: 0.30185407726094127
purpose: []
